export default {
  Localisation: {
    "Evolves from": {
      DE: "Entwickelt sich aus [Mst:CardCharacterName]",
      EN: "Evolves from [Mst:CardCharacterName]",
      ES: "Evoluciona de [Mst:CardCharacterName]",
      FR: "Évolution de : [Mst:CardCharacterName]",
      IT: "Si evolve da [Mst:CardCharacterName]",
      JP: "[Mst:CardCharacterName]から進化",
      KO: "[Mst:CardCharacterName]에서 진화",
      PT: "Evolui de [Mst:CardCharacterName]",
      ZH: "從[Mst:CardCharacterName]進化",
    },
    HP: {
      DE: "KP",
      EN: "HP",
      ES: "PS",
      FR: "PV",
      IT: "PS",
      JP: "HP",
      KO: "HP",
      PT: "PS",
      ZH: "HP",
    },
    Illustrator: {
      DE: "Illustr.",
      EN: "Illus.",
      ES: "Ilus.",
      FR: "Illus.",
      IT: "Ill.",
      JP: "Illus.",
      KO: "Illus.",
      PT: "Ilust.",
      ZH: "Illus.",
    },
    Retreat: {
      DE: "Rückzug",
      EN: "retreat",
      ES: "Retirada",
      FR: "Retraite",
      IT: "ritirata",
      JP: "にげる",
      KO: "후퇴",
      PT: "Recuo",
      ZH: "撤退",
    },
    Weakness: {
      DE: "Schwäche",
      EN: "weakness",
      ES: "Debilidad",
      FR: "Faiblesse",
      IT: "debolezza",
      JP: "弱点",
      KO: "약점",
      PT: "Fraqueza",
      ZH: "弱點",
    },
  },

  Backgrounds: {
    Dark: require("@/assets/images/Pokemon Cards/Card Assets/Backgrounds/Dark.png"),
    Dragon: require("@/assets/images/Pokemon Cards/Card Assets/Backgrounds/Dragon.png"),
    Fighting: require("@/assets/images/Pokemon Cards/Card Assets/Backgrounds/Fighting.png"),
    Fire: require("@/assets/images/Pokemon Cards/Card Assets/Backgrounds/Fire.png"),
    Goods: require("@/assets/images/Pokemon Cards/Card Assets/Backgrounds/Goods.png"),
    Grass: require("@/assets/images/Pokemon Cards/Card Assets/Backgrounds/Grass.png"),
    Items: require("@/assets/images/Pokemon Cards/Card Assets/Backgrounds/Items.png"),
    Lightning: require("@/assets/images/Pokemon Cards/Card Assets/Backgrounds/Lightning.png"),
    Metal: require("@/assets/images/Pokemon Cards/Card Assets/Backgrounds/Metal.png"),
    Normal: require("@/assets/images/Pokemon Cards/Card Assets/Backgrounds/Normal.png"),
    Psychic: require("@/assets/images/Pokemon Cards/Card Assets/Backgrounds/Psychic.png"),
    Supporter: require("@/assets/images/Pokemon Cards/Card Assets/Backgrounds/Supporter.png"),
    Water: require("@/assets/images/Pokemon Cards/Card Assets/Backgrounds/Water.png"),
  },

  Rarity: {
    Crown: require("@/assets/images/Pokemon Cards/Card Assets/Rarity/Crown.png"),
    Diamond: require("@/assets/images/Pokemon Cards/Card Assets/Rarity/Diamond.png"),
    Star: require("@/assets/images/Pokemon Cards/Card Assets/Rarity/Star.png"),
  },

  Frames: {
    Common: require("@/assets/images/Pokemon Cards/Card Assets/Frames/Common.png"),
    Uncommon: require("@/assets/images/Pokemon Cards/Card Assets/Frames/Uncommon.png"),
    Rare: require("@/assets/images/Pokemon Cards/Card Assets/Frames/Rare.png"),
    FullArt: require("@/assets/images/Pokemon Cards/Card Assets/Frames/FullArt.png"),
    Gold: require("@/assets/images/Pokemon Cards/Card Assets/Frames/Gold.png"),
    Rainbow: require("@/assets/images/Pokemon Cards/Card Assets/Frames/Rainbow.png"),
    Immersive: require("@/assets/images/Pokemon Cards/Card Assets/Frames/Immersive.png"),
    Trainer: require("@/assets/images/Pokemon Cards/Card Assets/Frames/Trainer.png"),
  },

  Stage: {
    0: require("@/assets/images/Pokemon Cards/Card Assets/Stage/BasicDetails.png"),
    1: require("@/assets/images/Pokemon Cards/Card Assets/Stage/Stage1Details.png"),
    2: require("@/assets/images/Pokemon Cards/Card Assets/Stage/Stage2Details.png"),
    Gold0: require("@/assets/images/Pokemon Cards/Card Assets/Stage/GoldBasicDetails.png"),
    Gold2: require("@/assets/images/Pokemon Cards/Card Assets/Stage/GoldStage2Details.png"),
  },

  StageText: {
    DE: {
      0: require("@/assets/images/Pokemon Cards/Card Assets/Stage/Text/Basic/DE.png"),
      1: require("@/assets/images/Pokemon Cards/Card Assets/Stage/Text/Stage 1/DE.png"),
      2: require("@/assets/images/Pokemon Cards/Card Assets/Stage/Text/Stage 2/DE.png"),
    },
    EN: {
      0: require("@/assets/images/Pokemon Cards/Card Assets/Stage/Text/Basic/EN.png"),
      1: require("@/assets/images/Pokemon Cards/Card Assets/Stage/Text/Stage 1/EN.png"),
      2: require("@/assets/images/Pokemon Cards/Card Assets/Stage/Text/Stage 2/EN.png"),
    },
    ES: {
      0: require("@/assets/images/Pokemon Cards/Card Assets/Stage/Text/Basic/ES.png"),
      1: require("@/assets/images/Pokemon Cards/Card Assets/Stage/Text/Stage 1/ES.png"),
      2: require("@/assets/images/Pokemon Cards/Card Assets/Stage/Text/Stage 2/ES.png"),
    },
    FR: {
      0: require("@/assets/images/Pokemon Cards/Card Assets/Stage/Text/Basic/FR.png"),
      1: require("@/assets/images/Pokemon Cards/Card Assets/Stage/Text/Stage 1/FR.png"),
      2: require("@/assets/images/Pokemon Cards/Card Assets/Stage/Text/Stage 2/FR.png"),
    },
    IT: {
      0: require("@/assets/images/Pokemon Cards/Card Assets/Stage/Text/Basic/IT.png"),
      1: require("@/assets/images/Pokemon Cards/Card Assets/Stage/Text/Stage 1/IT.png"),
      2: require("@/assets/images/Pokemon Cards/Card Assets/Stage/Text/Stage 2/IT.png"),
    },
    JP: {
      0: require("@/assets/images/Pokemon Cards/Card Assets/Stage/Text/Basic/JP.png"),
      1: require("@/assets/images/Pokemon Cards/Card Assets/Stage/Text/Stage 1/JP.png"),
      2: require("@/assets/images/Pokemon Cards/Card Assets/Stage/Text/Stage 2/JP.png"),
    },
    KO: {
      0: require("@/assets/images/Pokemon Cards/Card Assets/Stage/Text/Basic/KO.png"),
      1: require("@/assets/images/Pokemon Cards/Card Assets/Stage/Text/Stage 1/KO.png"),
      2: require("@/assets/images/Pokemon Cards/Card Assets/Stage/Text/Stage 2/KO.png"),
    },
    PT: {
      0: require("@/assets/images/Pokemon Cards/Card Assets/Stage/Text/Basic/PT.png"),
      1: require("@/assets/images/Pokemon Cards/Card Assets/Stage/Text/Stage 1/PT.png"),
      2: require("@/assets/images/Pokemon Cards/Card Assets/Stage/Text/Stage 2/PT.png"),
    },
    ZH: {
      0: require("@/assets/images/Pokemon Cards/Card Assets/Stage/Text/Basic/ZH.png"),
      1: require("@/assets/images/Pokemon Cards/Card Assets/Stage/Text/Stage 1/ZH.png"),
      2: require("@/assets/images/Pokemon Cards/Card Assets/Stage/Text/Stage 2/ZH.png"),
    },
  },

  EvolvesFrom: {
    Doduo: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Doduo.png"),
    DomeFossil: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/DomeFossil.png"),
    Dragonair: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Dragonair.png"),
    Dratini: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Dratini.png"),
    Drowsee: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Drowsee.png"),
    Ducklet: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Ducklet.png"),
    Eelektrik: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Eelektrik.png"),
    Eevee: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Eevee.png"),
    Ekans: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Ekans.png"),
    Electabuzz: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Electabuzz.png"),
    Exeggcute: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Exeggcute.png"),
    Froakie: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Froakie.png"),
    Frogadier: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Frogadier.png"),
    Gastly: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Gastly.png"),
    Geodude: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Geodude.png"),
    Gloom: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Gloom.png"),
    Goldeen: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Goldeen.png"),
    Golett: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Golett.png"),
    Graveler: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Graveler.png"),
    Grimer: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Grimer.png"),
    Growlithe: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Growlithe.png"),
    Haunter: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Haunter.png"),
    Heliolisk: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Heliolisk.png"),
    HelixFossi: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/HelixFossil.png"),
    Horsea: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Horsea.png"),
    Ivysaur: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Ivysaur.png"),
    Jigglypuff: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Jigglypuff.png"),
    Kabuto: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Kabuto.png"),
    Kadabra: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Kadabra.png"),
    Kakuna: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Kakuna.png"),
    Kirlia: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Kirlia.png"),
    Koffing: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Koffing.png"),
    Krabby: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Krabby.png"),
    Lickitung: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Lickitung.png"),
    Machoke: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Machoke.png"),
    Machop: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Machop.png"),
    Magikarp: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Magikarp.png"),
    Magmar: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Magmar.png"),
    Magneton: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Magneton.png"),
    Mankey: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Mankey.png"),
    Megnemite: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Megnemite.png"),
    Meltan: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Meltan.png"),
    Meowth: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Meowth.png"),
    Metapod: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Metapod.png"),
    Mienshao: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Mienshao.png"),
    Minccino: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Minccino.png"),
    NidoranF: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/NidoranF.png"),
    NidoranM: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/NidoranM.png"),
    Nidorina: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Nidorina.png"),
    Nidorino: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Nidorino.png"),
    Oddish: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Oddish.png"),
    OldAmber: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/OldAmber.png"),
    Omanyte: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Omanyte.png"),
    Paras: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Paras.png"),
    Petilil: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Petilil.png"),
    Pidgeotto: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Pidgeotto.png"),
    Pidgey: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Pidgey.png"),
    Pikachu: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Pikachu.png"),
    Poliwag: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Poliwag.png"),
    Poliwhirl: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Poliwhirl.png"),
    Ponyta: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Ponyta.png"),
    Porygon: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Porygon.png"),
    Psyduck: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Psyduck.png"),
    Ralts: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Ralts.png"),
    Rattata: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Rattata.png"),
    Rhydon: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Rhydon.png"),
    Rhyhorn: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Rhyhorn.png"),
    Salandit: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Salandit.png"),
    Sanshrew: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Sanshrew.png"),
    Seel: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Seel.png"),
    Shellder: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Shellder.png"),
    Sizzlipede: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Sizzlipede.png"),
    Skidoo: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Skidoo.png"),
    Slowpoke: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Slowpoke.png"),
    Snom: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Snom.png"),
    Spearow: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Spearow.png"),
    Squirtle: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Squirtle.png"),
    Staryu: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Staryu.png"),
    Tangela: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Tangela.png"),
    Tentacool: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Tentacool.png"),
    Tynamo: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Tynamo.png"),
    Venonat: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Venonat.png"),
    Voltorb: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Voltorb.png"),
    Vulpix: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Vulpix.png"),
    Weedle: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Weedle.png"),
    Weepinbell: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Weepinbell.png"),
    Woobat: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Woobat.png"),
    Wooloo: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Wooloo.png"),
    Wortortle: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Wortortle.png"),
    Zubat: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Zubat.png"),
    Abra: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Abra.png"),
    Bellsprout: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Bellsprout.png"),
    Bisharp: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Bisharp.png"),
    Blitzle: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Blitzle.png"),
    Bulbasaur: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Bulbasaur.png"),
    Caterpie: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Caterpie.png"),
    Charmander: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Charmander.png"),
    Charmeleon: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Charmeleon.png"),
    Clefairy: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Clefairy.png"),
    Clobopuss: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Clobopuss.png"),
    Cottonee: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Cottonee.png"),
    Cubone: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Cubone.png"),
    Digglet: require("@/assets/images/Pokemon Cards/Card Assets/Pokemon Evo/Digglet.png"),
  },

  TypeSymbols: {
    Dark: require("@/assets/images/Pokemon Cards/Card Assets/Type Icons/Dark.png"),
    Dragon: require("@/assets/images/Pokemon Cards/Card Assets/Type Icons/Dragon.png"),
    Fighting: require("@/assets/images/Pokemon Cards/Card Assets/Type Icons/Fighting.png"),
    Fire: require("@/assets/images/Pokemon Cards/Card Assets/Type Icons/Fire.png"),
    Grass: require("@/assets/images/Pokemon Cards/Card Assets/Type Icons/Grass.png"),
    Lightning: require("@/assets/images/Pokemon Cards/Card Assets/Type Icons/Lightning.png"),
    Metal: require("@/assets/images/Pokemon Cards/Card Assets/Type Icons/Metal.png"),
    Normal: require("@/assets/images/Pokemon Cards/Card Assets/Type Icons/Normal.png"),
    Psychic: require("@/assets/images/Pokemon Cards/Card Assets/Type Icons/Psychic.png"),
    Water: require("@/assets/images/Pokemon Cards/Card Assets/Type Icons/Water.png"),
  },

  CardArt: {
    "A1 001": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 001.png"),
    "A1 002": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 002.png"),
    "A1 003": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 003.png"),
    "A1 005": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 005.png"),
    "A1 006": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 006.png"),
    "A1 007": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 007.png"),
    "A1 008": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 008.png"),
    "A1 009": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 009.png"),
    "A1 010": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 010.png"),
    "A1 011": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 011.png"),
    "A1 012": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 012.png"),
    "A1 013": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 013.png"),
    "A1 014": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 014.png"),
    "A1 015": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 015.png"),
    "A1 016": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 016.png"),
    "A1 017": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 017.png"),
    "A1 018": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 018.png"),
    "A1 019": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 019.png"),
    "A1 020": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 020.png"),
    "A1 021": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 021.png"),
    "A1 022": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 022.png"),
    "A1 024": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 024.png"),
    "A1 025": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 025.png"),
    "A1 026": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 026.png"),
    "A1 027": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 027.png"),
    "A1 028": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 028.png"),
    "A1 029": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 029.png"),
    "A1 030": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 030.png"),
    "A1 031": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 031.png"),
    "A1 032": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 032.png"),
    "A1 033": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 033.png"),
    "A1 034": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 034.png"),
    "A1 035": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 035.png"),
    "A1 037": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 037.png"),
    "A1 038": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 038.png"),
    "A1 039": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 039.png"),
    "A1 040": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 040.png"),
    "A1 042": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 042.png"),
    "A1 043": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 043.png"),
    "A1 044": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 044.png"),
    "A1 045": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 045.png"),
    "A1 046": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 046.png"),
    "A1 048": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 048.png"),
    "A1 049": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 049.png"),
    "A1 050": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 050.png"),
    "A1 051": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 051.png"),
    "A1 052": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 052.png"),
    "A1 053": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 053.png"),
    "A1 054": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 054.png"),
    "A1 055": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 055.png"),
    "A1 057": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 057.png"),
    "A1 058": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 058.png"),
    "A1 059": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 059.png"),
    "A1 060": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 060.png"),
    "A1 061": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 061.png"),
    "A1 062": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 062.png"),
    "A1 063": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 063.png"),
    "A1 064": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 064.png"),
    "A1 065": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 065.png"),
    "A1 066": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 066.png"),
    "A1 067": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 067.png"),
    "A1 068": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 068.png"),
    "A1 069": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 069.png"),
    "A1 070": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 070.png"),
    "A1 071": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 071.png"),
    "A1 072": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 072.png"),
    "A1 073": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 073.png"),
    "A1 074": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 074.png"),
    "A1 075": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 075.png"),
    "A1 077": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 077.png"),
    "A1 078": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 078.png"),
    "A1 079": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 079.png"),
    "A1 080": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 080.png"),
    "A1 081": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 081.png"),
    "A1 082": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 082.png"),
    "A1 083": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 083.png"),
    "A1 085": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 085.png"),
    "A1 086": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 086.png"),
    "A1 087": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 087.png"),
    "A1 088": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 088.png"),
    "A1 089": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 089.png"),
    "A1 090": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 090.png"),
    "A1 091": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 091.png"),
    "A1 092": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 092.png"),
    "A1 093": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 093.png"),
    "A1 094": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 094.png"),
    "A1 095": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 095.png"),
    "A1 097": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 097.png"),
    "A1 098": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 098.png"),
    "A1 099": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 099.png"),
    "A1 100": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 100.png"),
    "A1 101": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 101.png"),
    "A1 102": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 102.png"),
    "A1 103": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 103.png"),
    "A1 105": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 105.png"),
    "A1 106": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 106.png"),
    "A1 107": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 107.png"),
    "A1 108": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 108.png"),
    "A1 109": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 109.png"),
    "A1 110": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 110.png"),
    "A1 111": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 111.png"),
    "A1 112": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 112.png"),
    "A1 113": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 113.png"),
    "A1 114": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 114.png"),
    "A1 115": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 115.png"),
    "A1 116": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 116.png"),
    "A1 117": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 117.png"),
    "A1 118": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 118.png"),
    "A1 119": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 119.png"),
    "A1 120": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 120.png"),
    "A1 121": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 121.png"),
    "A1 122": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 122.png"),
    "A1 124": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 124.png"),
    "A1 125": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 125.png"),
    "A1 126": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 126.png"),
    "A1 127": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 127.png"),
    "A1 128": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 128.png"),
    "A1 130": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 130.png"),
    "A1 131": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 131.png"),
    "A1 132": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 132.png"),
    "A1 133": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 133.png"),
    "A1 134": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 134.png"),
    "A1 135": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 135.png"),
    "A1 136": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 136.png"),
    "A1 137": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 137.png"),
    "A1 138": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 138.png"),
    "A1 139": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 139.png"),
    "A1 140": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 140.png"),
    "A1 141": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 141.png"),
    "A1 142": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 142.png"),
    "A1 143": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 143.png"),
    "A1 144": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 144.png"),
    "A1 145": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 145.png"),
    "A1 147": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 147.png"),
    "A1 148": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 148.png"),
    "A1 149": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 149.png"),
    "A1 150": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 150.png"),
    "A1 151": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 151.png"),
    "A1 152": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 152.png"),
    "A1 154": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 154.png"),
    "A1 155": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 155.png"),
    "A1 156": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 156.png"),
    "A1 157": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 157.png"),
    "A1 158": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 158.png"),
    "A1 159": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 159.png"),
    "A1 160": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 160.png"),
    "A1 161": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 161.png"),
    "A1 162": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 162.png"),
    "A1 163": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 163.png"),
    "A1 164": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 164.png"),
    "A1 165": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 165.png"),
    "A1 166": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 166.png"),
    "A1 167": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 167.png"),
    "A1 168": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 168.png"),
    "A1 169": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 169.png"),
    "A1 170": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 170.png"),
    "A1 171": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 171.png"),
    "A1 172": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 172.png"),
    "A1 173": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 173.png"),
    "A1 174": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 174.png"),
    "A1 175": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 175.png"),
    "A1 176": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 176.png"),
    "A1 177": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 177.png"),
    "A1 178": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 178.png"),
    "A1 179": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 179.png"),
    "A1 180": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 180.png"),
    "A1 181": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 181.png"),
    "A1 182": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 182.png"),
    "A1 183": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 183.png"),
    "A1 184": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 184.png"),
    "A1 185": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 185.png"),
    "A1 186": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 186.png"),
    "A1 187": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 187.png"),
    "A1 188": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 188.png"),
    "A1 189": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 189.png"),
    "A1 190": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 190.png"),
    "A1 191": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 191.png"),
    "A1 192": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 192.png"),
    "A1 193": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 193.png"),
    "A1 194": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 194.png"),
    "A1 196": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 196.png"),
    "A1 197": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 197.png"),
    "A1 198": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 198.png"),
    "A1 199": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 199.png"),
    "A1 200": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 200.png"),
    "A1 201": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 201.png"),
    "A1 202": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 202.png"),
    "A1 203": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 203.png"),
    "A1 204": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 204.png"),
    "A1 205": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 205.png"),
    "A1 206": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 206.png"),
    "A1 207": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 207.png"),
    "A1 208": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 208.png"),
    "A1 209": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 209.png"),
    "A1 210": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 210.png"),
    "A1 211": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 211.png"),
    "A1 212": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 212.png"),
    "A1 213": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 213.png"),
    "A1 214": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 214.png"),
    "A1 215": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 215.png"),
    "A1 216": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 216.png"),
    "A1 217": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 217.png"),
    "A1 218": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 218.png"),
    "A1 219": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 219.png"),
    "A1 220": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 220.png"),
    "A1 221": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 221.png"),
    "A1 222": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 222.png"),
    "A1 223": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 223.png"),
    "A1 224": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 224.png"),
    "A1 225": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 225.png"),
    "A1 226": require("@/assets/images/Pokemon Cards/Card Assets/Pokemon/A1 226.png"),
  },
};
